services:
  - type: web
    name: mutant-detector-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./Mercado-Libre-JulianBeron
    envVars:
      - key: PORT
        value: "8080"
